Chjune android step 1
MalibinStudy/Lotto pull request #2
Opened 2020-11-15 07:45 UTC by CHJUNE-android

나름 생각하며 분리하고 짜봤는데 맞는진 잘 모르겠군여..ㅎㅎ
LottoInspectorTest.kt 의 테스트코드가 이렇게 하는것 보다 좋은 방법이 있을것 같다는 생각이 들고..
뷰와 도메인을 분리하는것에 신경을 쓰긴 했는데
마지막 당첨 결과를 보여주는 부분은 도메인이 아니라 뷰에서 처리하는게 맞는건지 헷갈리기도 하고 머리가 빙빙입니다^___^
갓혁님의 피드백 기다리겠습니닿ㅎㅎ

2020-11-15 11:39 UTC, nightmare73 requested changes

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
처음에 수정 불가능한 빈 리스트가 있고, 그걸 활용하는게 아니라 아예 새로 할당이되는 구조네!
몬가 비효율적인거같아

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +    }
내부적으로 랜덤한 값들을 생성했네. Lotto의 테스트 코드를 작성할 수 있을까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        return generatedLottos
map을 활용해보는건 어떨까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +    fun generateLotto(numOfLotto: Int): List<Lotto> {
아예 돈을 넣으면 생성하게 만드는건 어떨까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoInspector.kt
> +    }
로또 티켓을 검사해주는 놈이 따로 있어야할까?
로또 티켓 자체가 다른 로또티켓과 비교하는 로직을 갖고있는건 어떨까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Winner.kt
> +    SIX(6, 2000000000);
Winner 가 3명이란뜻일까?
처음에 와닿은 의미는 이런느낌이었어.

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Winner.kt
> +    }
얘는 여기서만 쓰는거라서 private 으로 바꾸거나, 아니면 그냥 밑에 find 람다에다가 인라인으로 넣어줘도 나쁘지않을거같아.

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Winner.kt
> +    }
enum 찾아내기 활용 👍👍👍

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Winner.kt
> +    }
그치만 !! 사용은 지양하자

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/view/BuyLottoResultView.kt
> +        println("총 수익률은 ${profitRatio}입니다.")
수익률을 계산하는 것과 몇개의 번호가 맞아서 몇등을 했는지의 로직이 과연 뷰 로직일까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/view/PurchaseInputView.kt
> +        return num
로또 가격의 예외처리가 과연 뷰의 일이 맞을까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/view/PurchaseLottoResultView.kt
> +        println("${numOfLottos}개를 구매했습니다.")
numOfLottos는 purchaedLottos 의 size로도 충분히 출력할 수 있을거같아

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/view/WinningInputView.kt
> +    }
로또 개수에 대한 예외처리가 과연 뷰로직에 있는게 맞을까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/view/WinningInputView.kt
> +    }
로또 숫자에 대한 예외처리가 뷰로직에 있는게 맞을까?

2020-11-15 11:39 UTC, nightmare73 commented on src/main/kotlin/lotto/view/WinningInputView.kt
> +    }
", " 이대로 입력받으면 불편하지않아..?
그냥 맘대로 " "나 ","로 커스텀해도돼 ㅋㅋㅋㅋ

2020-11-15 11:39 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoInspectorTest.kt
> +
List\<Lotto\> 는 일급 컬렉션을 활용해주세요

2020-11-15 11:39 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoTest.kt
> +internal class LottoTest {
로또 번호가 내가 원하는 대로 나오는지에 대한 테스트도 해야하지 않을까?

2020-11-15 11:39 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/WinnerTest.kt
> +    }
음.. 이건 의미가 없는 테스트인거같아. 오히려 몇개가 맞았으냐에 따라 맞는 Enum을 불러오는지 테스트하는게 좋지 않을까?

2020-11-15 11:39 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoInspectorTest.kt
> +    }
lottoInspector.inspectAll(generatedLottos, winningLotto).size
이거 너무 복잡한데 when 으로 끌어올리는게 나을거같아

2020-11-15 11:40 UTC, nightmare73 commented
전반적으로 핵심로직들이 뷰쪽으로 많이 흩어져있는거같아.
View 로직이 굉장히 분리되어있고 뭐가 많은데, 오히려 도메인 로직이 거기에 다 들어가버려서 많아진거라고 생각해. 딱 뷰를 떼고 클래스 4개만 딱 안드로이드나 다른곳으로 이식한다고 생각해보자. 엄청나게 많은 코드들이 재 작성되어야된다고 생각해.

또, 모든 컬렉션들은 모두 일급컬렉션으로 감싸서 작성해보자.

2020-11-15 16:51 UTC, nightmare73 commented
로또 번호는 이 미션에서 상당히 중요하고 의미있는 값이라고 생각하는데, 단순히 Int가 아닌 로또 번호에 해당하는 값 객체를 만들어보는건 어떨까?

2020-11-16 04:50 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/LottoGenerator.kt
> +        return generatedLottos
이걸 어캐 맵으로 바꿀수 있을까 모르겠군요....
val purchaseLottos = List(numOfLottos){ Lotto() }
대신 이렇게 numOfLottos만큼 리스트를 생성하는 방법을 찾긴 했습니다

map으로 변환하는 방법점 알려주실수 있나여 갓혁님

2020-11-17 13:47 UTC, l2hyunwoo reviewed
진짜 수고 많이 했어 형! 코드 보면서 내가 알고 있는 데 활용하지 못한 게 뭐가 있는 지 알아갈 수 있었던 것 같아. 개인적으로 궁금했던 것도 코멘트 달았고 리뷰한 내용 같이 코멘트 달았어 참고해줘

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +object InputChecker {
[Super 객체](https://github.com/MalibinStudy/Lotto/pull/3#discussion_r523784710) 관련 리뷰입니다. 참고해주세용

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +            it.toIntOrNull() ?: throw java.lang.IllegalArgumentException("숫자만 적어주세요 \n입력값: $winnerNumsString")
요건 위에 거하고 달리 kotlin IllegalArumentException이 아니네요. import할 때 실수로 다른거 눌렀나보다

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +        }
- 만약에 로또 번호가 바뀌어진다면? 상수는 Magic Number가 아닌 Constant로 담아야 한다는 말이 있습니다.
- 그리고 이 검증로직 같은 경우 LottoNumGenerator의 범위가 바뀐다면 이 클래스를 유지보수를 해야할텐데 차라리 한 클래스에 담는 것이 같이 보기에 더 쉬울 것 같습니다.

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +    }
다들 똑같이 했구나 ㅋㅋㅋㅋㅋ

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/LottoShop.kt
> +    }
- 나는 여기서 엄청 고민을 많이 했던게 "Test를 가능하게 만드려면 어떻게 해야할 까"였어 (난 이게 막판 가서야 눈에 보이더라고)
- 여기서는 generateLotto를 Test를 할 때, 개발자가 직접 통제를 할 수가 없어서 원하는 결과를 얻을 수 있는 테스트를 직접 수행하는 게 힘들었을 것 같아.
- 외부에서 Lotto 생성 방법을 받아올 수 있는 여지를 남겨놓는 게 좋지 않을까 하는 생각이 들어.

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/WinLotto.kt
> +    }
```suggestion
    fun getWinnerCount() = winnerCount
```
로 적어도 충분할 것 같아

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/WinLotto.kt
> +    }
배워갑니다(1)....

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/WinLotto.kt
> +}
배워갑니다(2).....

2020-11-17 13:47 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/ProfitCalculator.kt
> +class ProfitCalculator {
- 이건 내가 궁금해서 그런 건데 나는 변수가 선언되고 함수가 있을 때 class로 선언을 하거든
    - 함수만 있을 때 클래스 사용하는 경우는 거의 없긴 한데 있다면 Interface 구현체 만들 때
    - object도 그러는 경우가 있긴 하지만 전역에서 사용해야할 때 object를 써
    - 변수만 있을 때는 data class..

- 형이 클래스하고 object를 사용하는 기준을 알고싶어

2020-11-17 13:47 UTC, l2hyunwoo commented on src/test/kotlin/lotto/domain/InputCheckerTest.kt
> +            .hasMessage("로또 하나의 가격은 1000원입니다. 1000원 단위로 입력해주세요\n 입력값: $priceNum")
테스트 이름하고 메시지하고 안 맞는 것 같아. 테스트는 1000원 이상이면 다 OK로 되어있는데
메시지는 1000원 단위(1000/2000 등)로 입력해달라고 하네

2020-11-17 14:23 UTC, chaeppy reviewed
갱장히... 꼼꼼하시네요...?
((반성의 시간))
테스트코드는 호준님껄로 배워갑니다.... (반성)
글고 가독성이 넘 조아서 읽기 편했어요! ((제기준))
수고하셨어요!!!

2020-11-17 14:23 UTC, chaeppy commented on src/main/kotlin/lotto/Main.kt
> +    val profitCalculator = ProfitCalculator()
메인코드에서 이익 계산을 하셨네욥😊
저도 이거 고민 많이했는데 도대체 메인코드의 역할은 어디까지인걸까요!?

2020-11-17 14:23 UTC, chaeppy commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +        require(num > 999) { throw IllegalArgumentException("로또 하나의 가격은 1000원입니다. 1000원 단위로 입력해주세요\n 입력값: $num") }
요거 상수로 감싸주면 좋을 것 같아요!

2020-11-17 14:23 UTC, chaeppy commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +object InputChecker {
호옹이 그렇군여~~~~ 슈퍼객체,,,🤔
그래도 하나하나 검사하시다니,,, 정말 꼼꼼하시네요.. ((반성))

2020-11-17 14:23 UTC, chaeppy commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +        return generateRandomNums().take(LOTTO_ENTRY_NUM)
이렇게 하는거였네요....??? take,,, 배워갑니다,,, ((메모))

2020-11-17 14:23 UTC, chaeppy commented on src/main/kotlin/lotto/domain/LottoShop.kt
> +        return List(numOfLottos) { generateLottos(LottoNumGenerator.getGeneratedLottoNums()) }
먼가 그냥 Lotto(LottoNumGenerator.getGeneratedLottoNums())를 바로 해도 될것 같은데 generateLottos를 하신 이유가 궁금합니다아

2020-11-17 14:23 UTC, chaeppy commented on src/main/kotlin/lotto/domain/WinnerChecker.kt
> +class WinnerChecker {
오 위너를 체크하는 클래스를 따로 만드셨네요!!

2020-11-18 02:42 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +            it.toIntOrNull() ?: throw java.lang.IllegalArgumentException("숫자만 적어주세요 \n입력값: $winnerNumsString")
ㅋㅋㅋㅋㅋ 뭐지 이걸 잡아내다니

2020-11-18 02:54 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +        }
좋은 피드백 감삼다

2020-11-18 03:04 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/ProfitCalculator.kt
> +class ProfitCalculator {
나는 변수 함수가 존재하느냐로 클래스냐 인터페이스냐를 구분하지는 않고 서로 분리되어 있지 않고 긴밀하게 협력한다고 생각되는 기능들을 모아둘 때 또는 어떤 역할을 가진 존재를 정의할때 클래스를 만들어.
인터페이스는 어떤 기능을 수행해야 하는데 체크리스트 같은 존재로 생각하고 있고,
object를 사용하는 경우는 여러 장소에서 사용될 때 매번 생성하지 않고 이용하려고 사용하는거고.

정확한진 나도 잘 모르겠는데 이런 기준(?)으로 사용하는편이야

2020-11-18 03:04 UTC, CHJUNE-android commented on src/test/kotlin/lotto/domain/InputCheckerTest.kt
> +            .hasMessage("로또 하나의 가격은 1000원입니다. 1000원 단위로 입력해주세요\n 입력값: $priceNum")
오키오킹

2020-11-18 03:07 UTC, CHJUNE-android commented on src/main/kotlin/lotto/Main.kt
> +    val profitCalculator = ProfitCalculator()
우선은 결과뷰로 넘기려고 메인에서 계산결과 받아오도록 했는데 좀 더 생각해볼 필요가 있어 보이군여

2020-11-18 03:07 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +        require(num > 999) { throw IllegalArgumentException("로또 하나의 가격은 1000원입니다. 1000원 단위로 입력해주세요\n 입력값: $num") }
아 죠습니다 땡큐

2020-11-18 03:08 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +        return generateRandomNums().take(LOTTO_ENTRY_NUM)
https://medium.com/hongbeomi-dev/kotlin-collection-%ED%95%A8%EC%88%98-7a4b1290bce4
컬렉션 관련 미친 블로그 하나 추천드림다

2020-11-18 03:11 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/LottoShop.kt
> +        return List(numOfLottos) { generateLottos(LottoNumGenerator.getGeneratedLottoNums()) }
purchaseLottos는 말 그대로 로또를 구매하는 것에 그 기능이 있고,
generateLottos는 랜덤 번호를 가진 로또 하나를 생성하는 역할을 갖는다 생각해서 나눴습니다.
하나의 메소드가 하나의 일만 하도록..

2020-11-20 13:14 UTC, nightmare73 requested changes
운동할시간이라 있다가 이어서 하죠

2020-11-20 13:14 UTC, malibinYun commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +    }
로또 가격에 해당하는 정보는 로또 프로그램의 핵심 정보 중 하나이지 않을까?

2020-11-20 13:14 UTC, malibinYun commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +    }
로또넘버를 만드는 과정에서 숫자를 검증하는데 한번 더 할필요가 있을까?

2020-11-20 13:14 UTC, malibinYun commented on src/main/kotlin/lotto/domain/InputChecker.kt
> +    }
InputChecker는 결국 InputView에서만 쓰이니 이것도 결국 뷰의 영역이라고 생각해.
뷰가 도메인 핵심 정보를 들고있다고 생각해. 또 이 정보들이 도메인에 없지도 않아. 여러군데에 도메인로직들이 분산되어있으면 유지보수에 용이할까?

2020-11-20 13:14 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +    private val lottoNumRange = MINIMUM_LOTTO_NUM..MAXIMUM_LOTTO_NUM
이건 여전히 랜덤에 대해서 내가 제어할 수 있는 구조가 아닌거같아.

2020-11-20 13:14 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
로또 한장을 만들 때마다
제너레이터쪽에서 1~45개의 Lottonum 객체들을 만들어내는 작업을 하네.
먼가 차라리 완성된 티켓을 뽑아내는 객체를 하나 만드는게 어떨까. 머신이랑 넘버 제너레이터랑 몬가 하는일이 같은 느낌이랄까?
또, 만들어진 로또에 대해서 제어권을 내가 갖고있지 않아. 무슨 번호가 들어있는 티켓인지 테스트할 방법이 없어

2020-11-20 13:14 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoNumGenerator.kt
> +    }
호출될 때마다 1\~45까지 로또 번호 객체를 만들고 그걸 섞어서 내뿜네.
아예 1\~45까지의 로또 번호 들을 미리 만들어두고 섞은애들을 복사해주는건 어떨까
나라면 섞고 6개만 뽑아준담에 그걸 티켓으로 만들어주기까지 할듯

2020-11-20 13:14 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        val numOfLottos = purchaseCost.getValue() / LOTTO_PRICE_UNIT
돈에서 값을 꺼내서 갯수를 새지말고
로또 하나의 가격을 넘기면 그 가격에 몇개를 살 수 있는지 알려주는 메서드는 어떨까?
돈이 실제 물건 가격에 대한 갯수를 현실세계에서는 계산할 순 없지만. 이상한 나라의 객체세계에서는 가능한일이지 않을까?

2020-11-20 13:14 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +    }
흠 가독성 ㅆㅅㅌㅊ

2020-11-20 13:14 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/WinnerChecker.kt
> +    }
이놈이 로또를 서로 비교해서 결과를 뽑아내는 책임을 지닌거잖아? 책임 분리까진 좋은 접근이라고 봐.
하지만 메서드가 하는 로직들을 잘 보면, 로또티켓에서 로또 번호들을 직접 끄집어 낸 다음에 이걸 여기서 일일이 비교 후에 결과를 뱉어준단말이지.
로또 티켓의 자율성을 해치는 느낌이 들어. 책을 봤다면 충분히 이해할거라 생각해.

그래서 하는 생각은, 로또 티켓의 자율성을 믿으니, 로또 티켓 자체가 자기 자신의 객체와 비교하는 메서드를 갖는건 어떨까?

2020-11-20 16:44 UTC, nightmare73 approved these changes
매우 고생한 흔적이 느껴지는군요.
책을 읽으시더니 매우 분리를 잘 하시는군요. 역시 책을 읽어야됩니다. 짱입니다.
피드백을 존나게 많이 주고싶을 수 밖에 없군요. 매우 발전했습니다.
더 해도 좋고 다음 미션 2단계를 바로 진행해도 좋습니다. 원하는대로 해드리죠

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Money.kt
> +}
getValue가 필요하다면
```suggestion
data class Money(
    val value: Int
) {
    init {
        require(value > 0) { "돈이 이상해요 입력값: $value" }
    }
}
```
자바스타일 보다는 코틀린 프로퍼티를 이용해보자

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Money.kt
> +}
돈이라는 원시 값 포장 👍👍👍
돈이라는 값이 양수만을 보장하는 값 객체 👍👍👍

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +    }
set구현체 자체에서 toString이 오버라이드 되어 있어서 비슷하게 나옴 걍 lottoNums.toString() 해도 ㄱㅊ

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +    }
디버그를위해 보여주는 tostring인데 뭔가 로직이 들어간 기분이라 이상한느낌이랄까
차라리 joinToString을 쓰는게 더 나은듯

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +
3개 이하로 맞은 로또는 꽝이여서 null인데, 과연 null로 꽝을 표현하는게 맞을까?
WinLotto 자체에 꽝을 포함하는게 더 직관적이지 않을까?

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +    }
1,1,2,3,4,5,6 을 넣는다면 거르지 못할거같은데 라고 말하려했지만 다시 생각해보니 애초에 Set으로 중복번호를 막아뒀고 그 갯수를 세는거니 존나 괜찮은 로직인거같다는 생각을 했다

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/LottoNum.kt
> +    }
자바스타일도 좋지만 코틀린 프로퍼티를 활용해보자

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/LottoNum.kt
> +) {
내부 값이 변하지 않는 불변 객체 및 값 객체 👍👍👍

1~45의 번호를 쓸 때마다 계속 생성해주어야할까?
한 번 캐싱에 도전해보자.

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Lottos.kt
> +}
일급 컬렉션이긴 한데 뭔가 데이터를 담고만 있지 아무런 일도 하지 않네.
나 처음 클코 스터디 할 때 어떤 쌉고수님은 이런 클래스를 멍텅구리 클래스라고 불렀지

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/WinLotto.kt
> +            return values().find { it.hasCorrectNum(correctNum) } ?: throw IllegalArgumentException("당첨 이력이 없습니다.\n요청한 값: $correctNum")
당첨 이력이 없다는 말은 무슨 말인지 잘 모르겠어.

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +    }
"번호" 가 잘못 만들어진걸까?
이 에러메시지를 보았을 때 혼란을 줄 수 있을거같아

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/LottoNumTest.kt
> +    }
요건 paramiterized 테스트를 통해서 1~45 바운더리가 아닌 양끝 숫자들로 테스트해줘도 좋을거같아

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/LottoNumTest.kt
> +    }
뭘 테스트하고싶은진 알겠지만 그래도 제목은 꼭 작성하자

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/LottoTest.kt
> +        val otherLottoNum = setOf(LottoNum(1), LottoNum(3), LottoNum(5), LottoNum(7), LottoNum(9), LottoNum(11))
https://github.com/next-step/kotlin-lotto/pull/22#discussion_r465179495
이 링크를 참고해보자
합리적으로 설계된 여러개의 생성자는 객체의 유연함을 가져다 줘.

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/LottoTest.kt
> +    @Test
제목이 좀 모호한거같아.
좀 더 구체적으로 설명해보자.

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/LottoTest.kt
> +    }
toString까지 테스트할필요는 없어 ㅋㅋㅋㅋ toString은 디버그 용이야

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/MoneyTest.kt
> +        // then
걍 복사를 때리셨군요

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/WinLottoTest.kt
> +    }
ParameterizedTest 활용 👍👍👍👍
0,1,2 때도 테스트해줘야한다고 생각해.

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/WinLottoTest.kt
> +    }
과연 1개 2개만 맞은 결과가 Exception을 터트려야하는 결과일까?

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/data/WinLottoTest.kt
> +}
음.. 이건 불필요한 테스트같아

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/WinnerCheckerTest.kt
> +    @Test
테스트의 제목을 꼭 자세하게 쓰자. 테스트 코드는 설명서라는걸 잊지말구!
영어 메서드 명이라도 자세히 써주어야해

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoNumGeneratorTest.kt
> +    }
이 테스트가 과연 의미가 있을까?
요구사항이 10~20으로 바뀌어도 통과되는 테스트일텐데, 테스트의 신뢰도가 낮아보여.

2020-11-20 16:44 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoMachineTest.kt
> +        assertThat(lottoMachine.generatedLottos(purchaseCost).getLottos()[0]).isInstanceOf(Lotto::class.java)
내가 직접 로또 번호를 컨트롤 할 수 있게끔 설계를 바꿔보자.
이 테스트에서 클래스의 인스턴스를 비교하는건 의미가 없는거같아.

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/view/ResultView.kt
> +    fun showLottos(purchasedLottos: Lottos) {
view 테스트는 노우..

2020-11-20 16:44 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/ProfitCalculator.kt
> +        return kotlin.math.round(totalProfit / purchaseCost.getValue() * ONE_HUNDRED) / ONE_HUNDRED
map도 결국 컬렉션이니 일급컬렉션으로 묶어보는건 어떨까?

2020-11-25 13:08 UTC, nightmare73 approved these changes
이제 다음미션합시다

2020-11-25 13:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/InputChanger.kt
> +        const val NUM_OF_LOTTO_NUMS = 6
아직 이런걸 여기서 가지구있군요..

2020-11-25 13:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        val numOfLottos = purchaseCost.value / LOTTO_PRICE_UNIT
https://github.com/MalibinStudy/Lotto/pull/2#discussion_r527679566
이것이 반영이되지않앗군요

2020-11-25 13:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +        return lottoNums.map { it.value }.toString()
https://github.com/MalibinStudy/Lotto/pull/2#discussion_r527801641
ㅎㅎ

2020-11-25 13:08 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/LottoNum.kt
> +}
LottoNum.cache[46] 이런식으로 접근할수가 있는 구조야.
이게 과연 의도된 에러를 터트리게할까? "46번이라는 로또번호가 없어요" 라는 에러보다 ListBoundary Exception이 터지지 않을까?
캐시를 외부에 보여주는건 좋지않아. 메서드를 통해서 원하는 에러핸들링과 원하는 값들만 접근해서 줄 수 있게끔 짜는게 좋아.
캐시를 했으니 LottoNum의 생성자는 아예 private으로 외부로부터 막아버리는게 어떨까? 진수가 잘 짰으니 한번 참고해보셈

2020-11-25 13:08 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/LottoResult.kt
> +    CORRECT_TWO(2, 0),
3개 이하로 맞은건 어쨌든 0원인데 3개로 각각 존재할 필요가 있을까?

2020-11-25 13:08 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/Money.kt
> +    }
흠 난 돈이 음수만 아니면 된다고봐

2020-11-25 13:08 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/WinResults.kt
> +    }
LottoResult라는 EnumMap이기 때문에 다른 Enum이 들어가는 경우는 원초적으로 배제가돼. 그래서 EnumMap을 쓰는것도 있어. 그니까.. 당첨갯수가 0~6이 아닌 애들이 애초에 들어올 수가 없어 EnumMap을 쓰면

2020-11-25 13:08 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/data/WinResults.kt
> +    }
그보다 특정Enum에 해당하는 총금액을 뱉는 메서드를 만드는건 어떨까?
외부에서 result를 직접 접근하지 않는거지.

2020-11-25 13:08 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoMachineTest.kt
> +            )
https://github.com/MalibinStudy/Lotto/pull/2#discussion_r527811180
생성자!

2020-11-25 13:51 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/InputChanger.kt
> +        const val NUM_OF_LOTTO_NUMS = 6
오우.... 이런 쓰잘데기 없는게 아직 있는지 몰랐네요... 바로 지우겠습니다 ㅎ;;

2020-11-25 13:53 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/LottoMachine.kt
> +        val numOfLottos = purchaseCost.value / LOTTO_PRICE_UNIT
아.. 이것도 수정하겠습니더

2020-11-25 14:09 UTC, merged

2020-11-25 14:11 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/data/Lotto.kt
> +        return lottoNums.map { it.value }.toString()
조인투로 변경했심다..ㅎㅎ;;;