현우의 Lotto Step 1
MalibinStudy/Lotto pull request #3
Opened 2020-11-15 13:41 UTC by l2hyunwoo

최대한 열심히 코딩했습니다.
정말로 아쉬운 건 WinningResult에 갔을 때 DrawingMachine이 LotteryWallet과 강력히 결부되어서 테스트를 하기 매우 어려웠던 것.... 틈틈히 구조를 다시 때려박아야할 것 같습니다.

2020-11-15 17:21 UTC, nightmare73 requested changes

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Validation.kt
> +object Validation {
모든 검증로직들이 여기에 모여있는게 맞을까?
굉장히 응집도를 떨어뜨리는 주범이라고 생각해. 다른 객체들이 해야할 일들을 얘가 모두 도맡아 하고있는거잖아?
또, 이것과 관련있는객체들은 이 객체와 굉장히 결합도가 높아지겠지.
매우 슈퍼객체의 느낌이야.

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Validation.kt
> +    }
메서드 작성의 순서는 일반적으로 체이닝이 걸려있지 않은 메서드 다음에 내부에서 호출하는 메서드 순서가 컨벤션이야

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LotteryWallet.kt
> +
my 라는 말이 꼭 필요할까?

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LotteryWallet.kt
> +
지갑이 돈도 들고있고 번호도 들고있다라.
과연 올바른 책임을 가지고있는걸까?

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LotteryWallet.kt
> +    }
이 객체는 만들어질때마다 DrawingMachine이라는걸 내부적으로 생성하는구나.
만약 이 프로그램을 사용하는 사용자가 동시에 몇천만번의 요청을 보내면 몇천만번의 새로운 객체가 생기겠네. 성능상의 이점을 고려했을 때, 항상 새로운 객체가 필요할까?

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LotteryWallet.kt
> +    fun getMyLotto(): List<LottoNumber> = lotteryWallet.toList()
일급컬렉션을 활용해보자

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    private val lottoNumberList = mutableListOf<Int>()
로또 숫자인데 Int의 List를 들고있네. 전혀 안에 list를 들고있을거라고 예상하지 못했어.
나라면 LottoTicket 정도로 이름을 쓸거같아.

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
왜 생성자에서 이런식으로 빙빙 돌리는지 이해가 되지않아.

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/MatchLottery.kt
> +    }
6자리 로또 번호나, 6자리 당첨번호나 같은 로또번호들인거같은데,
하나는 LottoNumber로 추상화되어있는데 하나는 저수준의 추상화단계네. 서로 맞추는게 좋지않을까?

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/MatchLottery.kt
> +        return lottoNumberList.filter { winningNumber.contains(it) }.size
filter 대신에 count를 쓰는건 어떨까

2020-11-15 17:21 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/DrawingMachine.kt
> +    private val lottoSampleSpace: List<Int> = (start..end).toList()
내가 원하는 로또 번호에 대한 테스트가 가능할까?

2020-11-15 17:21 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/DrawingMachineTest.kt
> +    fun `로또의 시작 숫자가 끝보다 클 떄`() {
클 때 뭘한다는 뜻일까? 테스트명은 중요해

2020-11-15 17:21 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LotteryWalletTest.kt
> +    fun `돈을 입금하면 로또를 구매할 수 있습니다`(money: Int, expectedLottoAmount: Int) {
돈을 넣으면 구매할수있다는게 어떤 종류의 테스트를 한다는 의미인지 모르겠어.

2020-11-15 17:21 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/ValidationTest.kt
> +    fun `입력값이 음수인 경우`() {
어떤 입력값이 음수며, 무슨일이 발생하는걸까?

2020-11-15 17:21 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/ValidationTest.kt
> +        val inputNumberList = listOf<Int>(1, 3, 2, 4, 6, 5)
정렬안되어있는 인풋에 대해 Exception발생시키는게 자연스러울까?

2020-11-15 17:21 UTC, nightmare73 commented
전반적으로 객체들이 메시지를 던져서 상호작용하는것 보다 제어권을 지닌 객체가 다른 객체들의 자율성을 믿지않고 꺼내 쓰는 로직들이 많아. 메시지를 넘김으로써 객체들이 협력하게 만들어보자.
또, 테스트들이 핵심을 로직에 관련된 테스트가 매우 적어보여. 그냥 테스트 코드만 많아보이고 알맹이는 얼마 없는 기분이야.
https://github.com/MalibinStudy/Lotto/pull/6#issuecomment-727600926 참고해보자

공통으로, 로또 번호는 이 미션에서 상당히 중요하고 의미있는 값이라고 생각하는데, 단순히 Int가 아닌 로또 번호에 해당하는 값 객체를 만들어보는건 어떨까?

2020-11-15 17:22 UTC, nightmare73 commented
의미없는 커밋은 하지맙시다. 린트 검사는 pre commit 으로 충분히 거를수있었고, squash라는 좋은 기능이 있습니다.

2020-11-15 17:32 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/Validation.kt
> +object Validation {
object 클래스로 선언을 할까 전역함수로 선언을 할까 고민을 많이 했던 지점이에요. 
Validation 클래스 내의 함수는 "검증"이라는 카테고리로 모여있는 함수여서 일전에 Primitives 파일에 모든 원시형 클래스들을 모았던 것처럼 그걸 모티브 삼아서 검증 로직은 한 곳에 뭉쳐서 놓았어요.

2020-11-15 17:44 UTC, l2hyunwoo commented on src/test/kotlin/lotto/domain/ValidationTest.kt
> +        val inputNumberList = listOf<Int>(1, 3, 2, 4, 6, 5)
추첨이 된 당첨 번호는 이미 정렬된 상태여야 한다는 걸 생각했어요. 

로또 구매 번호가 정렬된 순서로 있다는걸 보고 
당첨번호도 정렬되어 있다는게 전제된 규칙인 것으로 생각해서
당첨 번호를 입력할 때 정렬이 안되어있으면 규칙에 어긋나있는 것으로 해석하는 쪽이 더 자연스럽다고 생각해서 exception을 터뜨린거에요

2020-11-15 17:46 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/LotteryWallet.kt
> +
일반적으로 내 지갑의 있는 돈으로 복권을 사는거니까 money보단 Wallet의 정체성을 높인다고 생각했어요

2020-11-15 17:48 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +    }
생각해보니까 바로 생성자에서 받아버리면 되네요;;

2020-11-15 18:05 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Validation.kt
> +object Validation {
케이스가 너무 다르다. Primitives는 각 응집도가 높은 클래스가 모여있지, 다른 애들이 해야할 일들이 뭉쳐져있는 집합체가 아니야. 위에서도 말했지만 매우 결합도가 높고 응집도가 매우 떨어지는 패턴이야

2020-11-15 18:07 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/ValidationTest.kt
> +        val inputNumberList = listOf<Int>(1, 3, 2, 4, 6, 5)
로또 구매번호는 읽기 좋게 편의성을 위해 정렬 해놓은거고, 인풋에 대해 정렬까지 요구하는건 난 오히려 사용자에 대해서 내 라이브러리 걍 쓰지 마라 라는 의미라고 생각해

2020-11-18 02:27 UTC, CHJUNE-android reviewed
고생많았습니다~ 느낀점들을 조금식 댓글 달아놨어요~

2020-11-18 02:27 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/DrawingMachine.kt
> +class DrawingMachine(start: Int, end: Int) {
DrawingMachine => 시작점부터 끝점까지 뭔가 그리는건가 싶은 이름이라는 생각이 드네요

2020-11-18 02:27 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/LotteryWallet.kt
> +        repeat(myMoney / LOTTO_UNIT_PRICE) {
myMoney / LOTTO_UNIT_PRICE를 따로 변수로 이름지어주고 repeat속에 넣으면 가독성이 더 좋지 않을까 생각해

2020-11-18 02:27 UTC, CHJUNE-android commented on src/main/kotlin/lotto/domain/MatchLottery.kt
> +object MatchLottery {
어떤건 이름이 Lotto고 어떤 경우는 Lottery로 되어있어서 통일하는건 어떨까 싶은 생각이 들었어

2020-11-18 02:27 UTC, CHJUNE-android commented on src/main/kotlin/lotto/view/InputView.kt
> +        val purchasePrice = readLine()!!.toInt()
오우.. 유저가 뭐 입력하느냐에 따른 예외처리를 해줘야 하지 않을까 싶어

2020-11-18 02:27 UTC, CHJUNE-android commented on src/main/kotlin/lotto/view/OutputView.kt
> +        }
나도 처음에 이게 뷰 역할 아닐까 생각했지만 이것저것 계산하는 도메인 로직으로 끄집어낼 수 있더라고
뷰는 표현만 하는 책임을 갖고있다고 생각하게 됐지

2020-11-24 14:26 UTC, l2hyunwoo reviewed
코드를 바꾸며 정말 많은 생각을 했습니다.
- 대부분의 iterator 처리를 함수형으로 바꿨습니다.
- Enum Class로 객체의 행동을 결정해봤습니다. 
- LottoShop 객체와 같은 경우 빌더 패턴을 슬깃 봐서 이를 활용하여 구현해봤습니다. 함수를 실행할 때 스토리가 이어지도록 설계를 해봤습니다.

진짜 뼈깎는 노력으로 코드바꿨습니다.

2020-11-25 13:31 UTC, nightmare73 approved these changes
일단 다음미션과 함께 피드백 반영을 해봅시다

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/LottoApplication.kt
> +        .sellsLottoTickets(purchasePrice)
https://www.yegor256.com/2016/02/03/design-patterns-and-anti-patterns.html
![image](https://user-images.githubusercontent.com/44341119/100232508-c6e78580-2f6b-11eb-9978-6be17244f9c2.png)

뭐 이런 의견도 있어

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/LottoApplication.kt
> +        .sellsLottoTickets(purchasePrice)
근데 로또샵을 빌드했는데 티켓이 결과로 튀어나오는건 이상하다
로또샵을 빌드하면 당연히 로또샵이 결과로 나와야된다고 생각해

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/LottoApplication.kt
> +        .sellsLottoTickets(purchasePrice)
추가적으로, 만약 install을 호출안하고 바로 sells를 호출한다면?
대부분의 빌더패턴은 자기자신을 다시 리턴하지 않고 Builder 객체를 따로 만들어서 마지막에 build()하는 순간 원하는 객체가 튀어나오게끔 만들어져있지

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/DrawingMachine.kt
> +    }
```suggestion
    private val lottoBalls = range.map { LottoNumber(it) }
```
차라리 이건어때

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/DrawingMachine.kt
> +class DrawingMachine(range: IntRange) : DrawingMethod {
Draw.... 로또는 카드가 아니라고 생각해
또, 로또 번호의 시작과 끝정보는 내생각엔 로또 번호 자체가 들고있는게 맞는 책임이라고봐 티켓이 갖고잇는게 아니라

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LotteryWinningCriteria.kt
> +    FIRST_PRIZE_TICKET(6, LottoPrizePolicy { FIRST_PRIZE });
그냥 이넘이 가격을 들고있는게 낫지않을까?
굳이 인터페이스에서 가격을 세팅하고 또 거기서 값을 꺼내오는 빙글빙글 돌아가는 방식을 택할 필요가있을까?

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LotteryWinningCriteria.kt
> +        }
winningnumber 가 당첨번호일것만 같은 착각에 빠지는걸
isWin은 무슨 의미인지 잘 모르겠어.

matchCount 이런게 더 번호가 몇개 맞았는지 알기 좋지않을까

2020-11-25 13:31 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/PrizeCheckList.kt
> +        return countResult.toList()
레퍼런스를 넘겨서 안에서 변경시킨다라... 누누히 말하지만 별로라고 생각해.
이케이스에선 충분히 map으로도 만들수있을거같고
또, 리턴되는 값들을 인덱스를 가지고 원하는값에 접근한다.. 리스트가 중간에 섞일 위험이 정말 없을까? 또는 다른사람이 이 List\<Int\>를 받았을 때 과연 이게 어떤 의미를 지닌 데이터 덩어리인지 알까?
나라면 그저 정수의 리스트라고밖에는 모를거같아

2020-11-25 13:31 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/DrawingMachineTest.kt
> +            )
https://github.com/MalibinStudy/Lotto/pull/2#discussion_r527811180
링크의 링크 이걸 한번 참고해보자

2020-11-25 13:31 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/DrawingMachineTest.kt
> +        )
이건 DrawingMachineTest가 아니라 LottoShop의 테스트같은데?

2020-11-25 13:31 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoBundleTest.kt
> +        val lottoBundle = LottoShop()
하는데?
테스트코드는 설명서야

2020-11-25 13:31 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +            .hasMessage("입력한 숫자는 로또 번호에 해당하지 않습니다. 입력한 번호: $input")
나는 이런경우 로또번호의 양끝인 0,46만 가지고 테스트해도 충분하다고봐

2020-11-25 13:34 UTC, nightmare73 commented
흠.. 몬가 현우는 자신만의 코딩스타일이 너무 강하게 박혀있는 느낌이 많이 들어.
솔직히 말하면 내가 가르치고있는게 맞나 싶을정도로 스타일이 강하달까?
이게 가독성이 좋거나 해석하기 좋고 유지보수에 좋다면 나도 그 스타일에 인정하지만, 적어도 내 수준에서 바라봤을 때는 그렇지 않다고 생각해. 물론 나도 조팝이라서 누구한테 뭐라할 입장은 안되긴하는데, 내가 알려주고있는 것들을 잘못파악하고 있는 기분이 들어. 객체지향의 사실과 오해 책 꼭 읽기바라

2020-11-25 14:09 UTC, merged