step1 로또 과제
MalibinStudy/Lotto pull request #6
Opened 2020-11-15 15:44 UTC by jinsu4755

만들면서 이게 맞나 싶네요... 정신이 없어서 후반에는 커밋하는것도 잊어버려서..한번에 그냥 뭉처버렸습니다..
아직까지도 많이 햇갈리네요..쥬륵..

2020-11-15 16:54 UTC, nightmare73 requested changes

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/WinningStatistics.kt
> +    private val statistics: MutableMap<Int, Int> = mutableMapOf(
이전에 배운 Enum을 활용해보는건 어떨까

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/view/InputView.kt
> +            }
900원을 입력하면 Exception이 자연스러울까 0개 티켓이 자연스러울까?

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
당첨번호에 관련된 로직이 뷰에있는게 맞을까?

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/view/InputView.kt
> +
로또의 가격을 뷰에서 갖고있는게 맞을까?

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/Lotto.kt
> +)
일급컬렉션 👍
하지만 아무런 일도 안하는 껍데기인거같네.
예전에 자바 클코스터디 할 때 상당한 고수였던분이 이런 클래스를 멍텅구리클래스라고 부르셨지

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoNumberRepository.kt
> +    }
List\<Int\> 를  일급컬렉션으로 묶어보자

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +    }
로또 금액이 뷰에도 있고 여기에도 있네.
만약 하나라도 금액이 바뀌면 유지보수에 영향을 미치지 않을까?

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +        return infomationOnLottoPurchased.toList()
map을 활용해보자.
List\<Lotto\>를 일급컬렉션으로 묶어보자.

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoWinningChecker.kt
> +        }
Lotto 객체의 것을 직접 꺼내지말고 메시지를 던져보자

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoWinningChecker.kt
> +) {
https://github.com/MalibinStudy/Lotto/pull/2#discussion_r523745368
참고해봅시다

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoWinningChecker.kt
> +    }
이게 어떤 상수를 의미하는건지 잘 모르겠어
2개 이하로 맞으면 꽝이라 그런건가?
그렇다면 몇등인지에 해당하는 정보인거같은데 여기에 위치하는게 맞을까?

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/RateOfReturn.kt
> +    }
https://github.com/next-step/kotlin-lotto/pull/22#discussion_r465173008
참고해봅시다

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/WinningStatistics.kt
> +        const val FIRST_PRIZE = 2000000000
```suggestion
        const val FIRST_PRIZE = 2_000_000_000
```
숫자가 길면 언더바로 표시해주는게 가독성이 더 좋아

2020-11-15 16:54 UTC, nightmare73 commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +    private val lottoNumberRepository = LottoNumberRepository()
이 로또 머신은 내가 랜덤에 대한 제어를 할 수 없겠다

2020-11-15 16:54 UTC, nightmare73 commented
전반적으로 테스트코드가 부족하네.
로또 번호가 1~45가 아닌경우, 원하는 번호를 가진 로또 티켓 테스트, 로또번호의 중복이 인풋으로 들어오는지 등등..
거의 모든 경우의 수를 다 생각해서 테스트를 만들어야해.
그런 예측가능한 에러를 막기 위해서 만드는게 테스트 코드니까. 예측 불가능한 에러가 터진다면... 테스트코드를 작성하는 의미가 없는거같아.

공통으로, 로또 번호는 이 미션에서 상당히 중요하고 의미있는 값이라고 생각하는데, 단순히 Int가 아닌 로또 번호에 해당하는 값 객체를 만들어보는건 어떨까?

2020-11-15 17:30 UTC, jinsu4755 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
음 뭔가 이전 당첨번호 관련된 분리가 필요할것 같네요..!

2020-11-17 14:39 UTC, l2hyunwoo reviewed
전반적으로 읽기 쉬웠던 것 같아. 고민한 지점이 어디에서 있는 지 알 수 있었던 것 같아. 근데 그걸 이미 멋지게 리뷰해준 사람이 있어서 ^^ 내가 적을 말이 그다지 없다. 
수고 했다 마, 같이 리팩토링 멋지게 해봅시더

2020-11-17 14:39 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/LottoVendingMachine.kt
> +    fun purchaseLotto(amount: Int): List<Lotto> {
내가 넣는 건 양이 아니라 "금액"이어서 amount라는 이름보다 price 같은 이름으로 바꿔야 나중에 헷갈리지 않을 것 같아

2020-11-17 14:39 UTC, l2hyunwoo commented on src/main/kotlin/lotto/domain/WinningStatistics.kt
> +    fun increase(matchNumberCount: Int) {
뭘 increase하는 건지 명시해줬으면 좋겠어

2020-11-25 14:08 UTC, nightmare73 approved these changes
다음 미션 기

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +        }
나라면 companion object 안에 만들기 보다 Lottonumber 안의 클래스로 만들었을듯. 스태틱으로 쓰고싶으면 object를 쓰고.

그니까 나라면 private object LottoNumberCache {} 를 사용했을듯

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +            return LottoNumberCache.cache[number - 1]
캐시 배열을 직접 꺼내는것보다 캐시에서도 메시지를 던져서 값을 꺼내오는건 어떨까

LottoNumberCache.of(number)
이런식

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoNumber.kt
> +) {
와 생성자를 닫을생각을 했네 존나굳임 👍👍👍👍
닫지않으면 캐싱을 하는 의미가 없으니까.

private 생성자를 하면 data class를 못쓰게되는데, 이런 경우 equals를 제대로 활용하기 어려워지니까
알트 인서트 눌러서 equals and hashcode를 오버라이드 해주는게 좋아 자동으로 생성해줘.

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoResult.kt
> +
호우.... 진수 쫌 하는데?
솔직히 감동했다
내코드본거아니지? 나랑 거의 같음

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +    }
이건 sumBy{} 라는 확장함수가 있단다
그걸 쓰면 map 따윈 쓰지 않아도 돼
아니면 reduce를 활용해도 좋고

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoStatistics.kt
> +    fun countWinningWith(lottoResult: LottoResult): Int = values[lottoResult] ?: 0
values를 직접 접근하지 않앗군... 👍
보람이있네... 슈벌...

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +
흠 검증을 하는데 List가 튀어나온다?
also를 활용하는건 좋지만 이건 별로라고 봐. 검증은 검증만 할 뿐.

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +            .count { otherLottoTicket.hasLottoNumber(it) }
맞은 개수만 반환하는게 아니라 아예 몇등인지 반환하는게 어떨까?

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoTicket.kt
> +    }
has() 라고 써도 이해하기 좋다고봐
그나저나 메시지 던지는거 잘했네...흠...

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoTicketDispenser.kt
> +        val amountOfTicket = cost / LottoTicket.LOTTO_PRICE
원시값을 포장해서 Money 객체도 만들어보자

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/LottoTicketGenerator.kt
> +    }
아예 인풋에서 int로 걸러서 들어오거나,
LottoNumber의 팩터리 메서드가 String을 갖는놈을 만들어서 거기서 터트리는게 좋을거같아.
숫자에 대한 검증로직이 제너레이터에 있으니까 어색해보여.

2020-11-25 14:08 UTC, malibinYun commented on src/main/kotlin/lotto/domain/StatisticalGenerator.kt
> +    }
ㅋㅋㅋㅋㅋ 결국 groupingBy를 찾으셨군요 축하합니다 🎉🎉

근데 결국 이 클래스는 티켓뭉치에서 값을 꺼내서  그걸로 지지고볶고 하는거잖아?
그럼 차라리 PurchasedLottoTickets 안에 이 로직이 있는게 낫지 않을까?
지금은 결합도만 높지 양 클래스가 너무 껍데기만 있는 느낌이야. 응집도를 높혀보자.

2020-11-25 14:08 UTC, nightmare73 commented on src/main/kotlin/lotto/view/InputView.kt
> +        }
엥모야 뷰에서 Ticket을 갖고잇다니 이상하군뇨

2020-11-25 14:08 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoNumberGenerateStrategyTest.kt
> +        val expectedTicket = LottoTicketGenerator().makeLottoTicket("1,2,3,4,5,6".split(","))
테스트에서 비교가 되는 대상을 만들 때 로직이 들어가선 안돼.
저렇게 써놨지만 내부적으로 어떤 티켓을 만들지는 절대로 모르거든. 스트링은 1,2,3,4,5,6 이라고 써져있지만 사실 내부적으로는 10,11,45,12,45,1 이딴걸 만들어냈다면?
로직을 타고들어가야하는 코드는 테스트코드에 쓰지 않는게 좋아.

2020-11-25 14:08 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoNumberTest.kt
> +            .isEqualTo(true)
그리고 번호도 1인지도 비교해주면 좋겠다. Lottonum의 value가 public으로 뚫려있기도하니까.
아마 여기에 접근안해서 테스트 커버리지 낮은것도 있었겠네.

2020-11-25 14:08 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoTicketGeneratorTest.kt
> +        val inputLastWeekLottoNumbers = "1,2,3,4,5,6".split(",")
list에 담아서하는게 베스트

2020-11-25 14:08 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoTicketGeneratorTest.kt
> +        // when
로직이 들어가면 안돼.
일일이 너가 직접 넣는게 훨씬 가독성이 좋아. 테스트코드는 일일이 하나씩 알려주는 설명서라는점을 잊어선 안돼.

2020-11-25 14:08 UTC, nightmare73 commented on src/test/kotlin/lotto/domain/LottoTicketTest.kt
> +    }
로직은 노우

2020-11-25 14:09 UTC, merged